#Custom Installer
#Version 2.0 Preview - Powered by danbenba

#-----------------------------------------------------Configuration du Logiciel------------------------------------------------------#

#Configuration pour l'application
app.title=Custom Installer (Preview Version)
app.iconPath=/icon.png
app.mainImage=https://raw.githubusercontent.com/danbenba/CustomInstaller/project/webFiles/CustomInstallerBanner.png

#Configuration du GUI (Indisponible en mode preview)
app.baner.dimetion=50, 10, 400, newHeight + 20
app.color=#c8c8c8

#Urls de configuration
version.url=https://raw.githubusercontent.com/danbenba/CustomInstaller/project/webFiles/appversion
terms.url=https://raw.githubusercontent.com/danbenba/CustomInstaller/project/webFiles/terms
download.url=https://github.com/danbenba/CustomInstaller/raw/project/webFiles/CustomInstaller.zip

#Text "Version 2.0 Preview" (Attention ne pas modifier les textes suivants : "<html><a href=''>" et "</a></html>")
link.name=<html><a href=''>Version 2.0 Preview</a></html>
link.url=https://github.com/danbenba/CustomInstaller

#Emplacements
dir.user=\\CustomInstaller
dir.progfile=C:\\CustomInstaller

#-----------------------------------------------------------------------------------------------------------------------------------#
